version: '3.8'
services:
  mysql:
    image: mysql:9.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD= # Replace with a strong password!
      - MYSQL_ALLOW_EMPTY_PASSWORD=true  # Only for development, remove in production!
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./db/mysql:/var/lib/mysql" # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
  petclinic:
    build:
      context: .  # The directory containing the Dockerfile
      dockerfile: Dockerfile  # Specifies the Dockerfile to use
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql  # Activate the MySQL profile
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic # Connect to MySQL service
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic
    depends_on:
      mysql:
        condition: service_healthy # Start petclinic after MySQL is healthy
    volumes:
      - .:/app # Mount project for potential live reloading (dev only)
    working_dir: /app # Set working directory for the command
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=mysql"] # Run the app
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
